### ISSUE TITLE
cannot run on windows: main loop fails

### ISSUE THREAD

**Issue by fdncred** [amtoine/nu_plugin_explore#1]
Was playing around to see what your plugin did and got this panic on Windows. I realize the plugin isn't ready but I was just playing around.
![image](https://github.com/amtoine/nu_plugin_explore/assets/343840/86ac89ec-20d9-41fc-a881-32e2a0d08b1a)

**Comment by amtoine** [comment]
ooh nice, some early feedback :smirk: 

can you share the steps that lead to that panic? :yum:

**Comment by amtoine** [comment]
and maybe retry with the latest build, i've added a bunch of commits tonight :relieved:

**Comment by fdncred** [comment]
Just compiled the latest. This is the same command above as well.

```nushell
❯ open Cargo.toml | explore
Error:   × unexpected error
   ╭─[entry #3:1:1]
 1 │ open Cargo.toml | explore
   ·                   ───┬───
   ·                      ╰── app loop failed
   ╰────
```

**Comment by amtoine** [comment]
mm i'm not able to reproduce this at all on my system :confused: 


> ```nushell
> Error:   × unexpected error
>    ╭─[entry #3:1:1]
>  1 │ open Cargo.toml | explore
>    ·                   ───┬───
>    ·                      ╰── app loop failed
>    ╰────
> ```
>
do you really see the error like this, with `miette`? :open_mouth:

**Comment by fdncred** [comment]
Yes, that is the error that I see. Maybe the problem is that you named the plugin the same name as our `explore` command? Maybe I'll rename it and try again.

**Comment by fdncred** [comment]
ok, i renamed it `nu_plugin_xplor` to make it unique. What happens is it loads the cargo.toml, switches to an alternate screen, draws something, fails and goes back to the prompt.

1. Load cargo.toml
![image](https://github.com/amtoine/nu_plugin_explore/assets/343840/326ada59-0eda-409d-b22b-f37b1ea486e5)
2. 3ms later this pops up
![image](https://github.com/amtoine/nu_plugin_explore/assets/343840/ac999686-d2f6-4ce5-a4d1-4bb698cce297)
3. 30 ms later this shows up
![image](https://github.com/amtoine/nu_plugin_explore/assets/343840/4d47b9dc-eddb-456a-8ac0-1d6e990ec4df)

gif
![xplor](https://github.com/amtoine/nu_plugin_explore/assets/343840/3ce59356-7f6a-4940-bc3b-c2c1701c758e)

**Comment by amtoine** [comment]
mm wow, i have no idea where this is coming from, i've never seen this error :open_mouth:

**Comment by amtoine** [comment]
not sure the name is the issue at least, because i've been using my own `explore` for a few days now without any issues apart from bad programming from my side :eyes: :laughing:

**Comment by fdncred** [comment]
Maded it a little further on this issue. I took out the context error message and replaced it with this
```rust
    let result = app::run(&mut terminal, input, &config);
    eprintln!("app loop result: {:?}", &result);
```
and on Windows it produces this.
```
❯ open Cargo.toml | explore
Error:   × unexpected error
   ╭─[entry #51:1:1]
 1 │ open Cargo.toml | explore
   ·                   ───┬───
   ·                      ╰── Incorrect function. (os error 1)
   ╰────
```
Which I tracked down to this https://github.com/console-rs/console/issues/35. So, I'm wondering if this is a console crate issue now.

**Comment by amtoine** [comment]
i'll open a PR and implement the template, hope this will fix the issue without introducing regressions into the explorer :pray:
