### ISSUE TITLE
why no cargo.lock file?

### ISSUE THREAD

**Issue by fdncred** [amtoine/nu_plugin_explore#34]
seems this repo is missing the cargo.lock file and i'm not sure why.

**Comment by Lykos153** [comment]
I guess that's why https://github.com/amtoine/nu_plugin_explore/blob/main/.gitignore#L6
```
 # Remove Cargo.lock from gitignore if creating an executable, leave it for libraries
 # More information here https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html
```

**Comment by fdncred** [comment]
i agree that it seems like it should be added. it messes up my script that builds plugins semi-automated.
